year: 2020
title: Carmen Lai
email: cglai8+website@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://carmenlai.com"
twitter_username: _carmenlai
github_username: ocarmieo
linkedin_username: carmenlai
youtube_username: carmenggg
disqus_shortname: carmenlai
instagram_shortname: carmenphotog
google_scholar_user_id: SWQL1o0AAAAJ

date_format_long: "%B %-d, %Y"

# Pagination
paginate: 3
paginate_path: "/blog/page:num/"

# Collections
collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  music:
    output: true
    permalink: /music/:path/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Carmen Lai"
      comments: true
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      author: "Carmen Lai"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
exclude:
  - Gemfile
  - Gemfile.lock
whitelist:
- jekyll-redirect-from
